"""
sentinel-harness · harness → Strands Agent code exporter (no lock-in)
=====================================================================
The escape hatch. ``export_harness_to_strands`` turns a loaded harness config
(the kwargs dict returned by :func:`sentinel_harness.loader.load_harness_config`)
into **editable Strands Agent Python source** — a starting point to run the same
agent on AgentCore Runtime or self-hosted, off the managed harness.

Why this exists
---------------
A managed harness is convenient, but a world-class platform must let a team walk
away with their config. This emitter reads model id / system prompt / tool
allowlist / memory shape from the config and writes a Strands ``Agent`` skeleton
the team owns and edits — no vendor lock-in.

Contract
--------
- **Pure + offline.** No AWS calls, no network, no clock, no randomness — the
  same config always yields byte-identical output (deterministic).
- **Emits text, never imports Strands.** The returned string is a *code artifact*.
  It contains ``from strands import ...`` lines that only run when the team later
  executes the file where ``strands-agents`` is installed; this module itself
  imports nothing from strands.
- **Valid Python.** The output parses with ``ast.parse`` / compiles with
  ``py_compile``.

Nothing in this file is customer- or company-specific.
"""
from __future__ import annotations

_HEADER = '''"""
Strands Agent — exported from a sentinel-harness config (NO-LOCK-IN escape hatch).
================================================================================
This is EDITABLE STARTER CODE, generated by ``sentinel export``. It mirrors a
managed AgentCore Harness (model / system prompt / tool allowlist / memory) as a
self-owned Strands Agent, so you can run the same agent on AgentCore Runtime or
self-hosted and walk away from the managed harness at any time.

To run it:
    pip install strands-agents          # and any tool/gateway/MCP deps you wire
    python this_file.py

The harness allowlist is reproduced below as comments + an ALLOWED_TOOLS binding.
Gateway tools (``@gateway/...``) map to an MCP client; inline_function HITL gates
map to Strands ``@tool`` functions you implement. Wire the ones you need into the
``tools=`` list, then edit freely — this file is yours.
"""'''


def _py_str(text: str) -> str:
    """Render ``text`` as a valid triple-quoted Python string literal.

    Escapes backslashes and any embedded ``\"\"\"`` and always terminates with a
    newline before the closing quotes so a trailing ``"`` can never merge with the
    delimiter. Deterministic: pure function of the input.
    """
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    # Leading backslash-newline keeps the content starting at column 0; trailing
    # newline guarantees the closing delimiter is unambiguous.
    return '"""\\\n' + body + '\n"""'


def _extract_model(config: dict) -> tuple[str | None, int | None, float | None]:
    """Pull (modelId, maxTokens, temperature) out of the config's model block.

    Accepts the shipped ``{"bedrockModelConfig": {...}}`` shape as well as a bare
    model-id string. Returns Nones for anything absent."""
    model = config.get("model")
    if model is None:
        return None, None, None
    if isinstance(model, str):
        return model, None, None
    if isinstance(model, dict):
        bmc = model.get("bedrockModelConfig", model)
        if isinstance(bmc, dict):
            return bmc.get("modelId"), bmc.get("maxTokens"), bmc.get("temperature")
    return None, None, None


def _system_prompt_text(config: dict) -> str:
    """Normalize the system prompt to a plain string (loader returns a string; a
    ``[{"text": ...}]`` list is also accepted and flattened)."""
    sp = config.get("system_prompt")
    if isinstance(sp, str):
        return sp
    if isinstance(sp, list):
        parts = [b.get("text", "") if isinstance(b, dict) else str(b) for b in sp]
        return "\n".join(p for p in parts if p)
    if sp is None:
        return ""
    return str(sp)


def export_harness_to_strands(config: dict) -> str:
    """Render a loaded harness config into editable Strands Agent Python source.

    ``config`` is the kwargs dict from ``loader.load_harness_config`` (keys:
    ``name``, ``system_prompt``, optional ``model`` / ``tools`` / ``memory`` /
    ``allowed_tools`` / ``max_iterations`` / ``timeout_seconds``). Returns valid,
    deterministic Python as a string. Emits code as TEXT — never imports strands.
    """
    name = config.get("name") or "exported_agent"
    model_id, max_tokens, temperature = _extract_model(config)
    system_prompt = _system_prompt_text(config)
    allowed_tools = list(config.get("allowed_tools") or [])
    max_iterations = config.get("max_iterations")
    timeout_seconds = config.get("timeout_seconds")
    memory = config.get("memory")

    lines: list[str] = []
    lines.append(_HEADER)
    lines.append("")
    lines.append("from strands import Agent")
    lines.append("from strands.models import BedrockModel")
    lines.append("")
    lines.append(f"# Exported from harness: {name}")
    lines.append("")

    # --- Model -------------------------------------------------------------
    if model_id:
        # Full model id is preserved verbatim (version suffix matters — an
        # unversioned id can fail silently on invoke).
        lines.append(f"MODEL_ID = {model_id!r}")
    else:
        lines.append("# No model was pinned in the harness config; set one here.")
        lines.append('MODEL_ID = "global.anthropic.claude-sonnet-4-5-20250929-v1:0"')
    lines.append(f"MAX_TOKENS = {int(max_tokens) if max_tokens is not None else 4096}")
    lines.append(
        f"TEMPERATURE = {float(temperature) if temperature is not None else 0.2}"
    )
    lines.append("")

    # --- System prompt -----------------------------------------------------
    lines.append("SYSTEM_PROMPT = " + _py_str(system_prompt))
    lines.append("")

    # --- Tool allowlist ----------------------------------------------------
    lines.append("# --- Tool allowlist (reproduced from the harness) ---------------------")
    lines.append("# Each entry below was in the harness `allowedTools`. Wire the ones you")
    lines.append("# need and append them to the tools=[...] list in build_agent().")
    lines.append("#   name                     -> a Strands @tool or builtin")
    lines.append("#   @gateway/<action>        -> an MCP client tool (AgentCore Gateway)")
    lines.append("#   request_*_approval       -> a human-in-the-loop @tool gate you own")
    if allowed_tools:
        for t in allowed_tools:
            lines.append(f"#   - {t}")
    else:
        lines.append("#   (none declared)")
    lines.append("ALLOWED_TOOLS = [")
    for t in allowed_tools:
        lines.append(f"    {t!r},")
    lines.append("]")
    lines.append("")

    # --- Memory note -------------------------------------------------------
    lines.append("# --- Memory -----------------------------------------------------------")
    if isinstance(memory, dict):
        mmc = memory.get("managedMemoryConfiguration")
        acm = memory.get("agentCoreMemoryConfiguration")
        if isinstance(mmc, dict):
            strategies = mmc.get("strategies")
            expiry = mmc.get("eventExpiryDuration")
            lines.append(
                "# The harness used AgentCore managed memory with strategies: "
                f"{strategies!r}"
            )
            if expiry is not None:
                lines.append(f"# (event expiry: {expiry} days).")
            lines.append(
                "# Off the managed harness, back this with an AgentCore Memory resource"
            )
            lines.append(
                "# (bedrock-agentcore Memory) or your own store, and inject recalled"
            )
            lines.append("# context into SYSTEM_PROMPT or via a retrieval tool.")
        elif isinstance(acm, dict):
            lines.append(
                "# The harness used a bring-your-own AgentCore Memory resource:"
            )
            lines.append(f"#   arn = {acm.get('arn')!r}")
            lines.append(
                "# Point your own memory client at it, or swap in another store."
            )
        else:
            lines.append("# Custom memory config detected; port it to your own store.")
    else:
        lines.append("# No memory was configured on the harness (stateless).")
    lines.append("")

    # --- Loop knobs (informational) ---------------------------------------
    if max_iterations is not None or timeout_seconds is not None:
        lines.append("# Harness loop guardrails (enforce these yourself off-harness):")
        if max_iterations is not None:
            lines.append(f"#   max_iterations  = {max_iterations}")
        if timeout_seconds is not None:
            lines.append(f"#   timeout_seconds = {timeout_seconds}")
        lines.append("")

    # --- Builder + entry point --------------------------------------------
    lines.append("def build_agent() -> Agent:")
    lines.append('    """Construct the exported agent. Add wired tools to tools=[...]."""')
    lines.append("    model = BedrockModel(")
    lines.append("        model_id=MODEL_ID,")
    lines.append("        max_tokens=MAX_TOKENS,")
    lines.append("        temperature=TEMPERATURE,")
    lines.append("    )")
    lines.append("    return Agent(")
    lines.append("        model=model,")
    lines.append("        system_prompt=SYSTEM_PROMPT,")
    lines.append("        tools=[],  # <- wire ALLOWED_TOOLS entries here")
    lines.append("    )")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    agent = build_agent()")
    lines.append('    reply = agent("Describe your task and produce a first result.")')
    lines.append("    print(reply)")
    lines.append("")

    return "\n".join(lines)
